### ISSUE TITLE
Returning `job_data_out` of a wrong job id

### ISSUE THREAD

**Issue by khsrali** [eth-cscs/firecrest#201] opened 2024-06-21 10:28 UTC
Note: I use pyfirecrest for convenience, but this issue seems to be from this repo, as pyfirecrest is only passing the message.

I'm submitting a job (on `daint`), but in response  `job_data_out` returned value is tailing the status of 54049707 instead of 54050460.
This seems to be a problem with parsing somewhere, see `time=N/A`

```python
{
    'job_data_err': '', 
    'job_data_out': '----------- ------------ -------- -------------\n    akhosrav         mr32       normal        1     13.533 kJ\n\n\n\nBatch Job Summary Report (version 21.01.1) for Job "aiida-45" (54049707) on daint\n\nJob information (1/2)\n-----------------------------------------------------------------------------------------------------\n             Submit            Eligible               Start                 End    Elapsed Time limit\n------------------- ------------------- ------------------- ------------------- ---------- ----------\n2024-06-21T10:45:38 2024-06-21T10:45:38 2024-06-21T10:45:39 2024-06-21T10:49:46   00:04:07   00:30:00\n-----------------------------------------------------------------------------------------------------\n\nJob information (2/2)\n-------------------------------------------------------------\n    Username      Account    Partition   NNodes        Energy\n------------ ------------ ------------ -------- -------------\n    akhosrav         mr32       normal        1     13.613 kJ\n', 
    'job_file': '/scratch/snx3000/akhosrav/submission_tests/_aiidasubmit_1.sh', 
    'job_file_err': '/scratch/snx3000/akhosrav/submission_tests/_scheduler-stderr.txt', 
    'job_file_out': '/scratch/snx3000/akhosrav/submission_tests/_scheduler-stdout.txt', 
    'job_info_extra': 'Job info returned successfully', 
    'jobid': '54050460', 
    'name': 'aiida-45', 
    'nodelist': '(Priority)', 
    'nodes': '1', 
    'partition': 'normal', 
    'start_time': '0:00', 
    'state': 'PENDING', 
    'time': 'N/A', 
    'time_left': '30:00', 
    'user': 'akhosrav'
}
```

Note some other times, this works as expected, in these cases `time` is not `N/A`

```python
{
  'job_data_err': '', 
  'job_data_out': '', 
  'job_file': '/scratch/snx3000/akhosrav/submission_tests/_aiidasubmit_1.sh', 
  'job_file_err': '/scratch/snx3000/akhosrav/submission_tests/_scheduler-stderr.txt', 
  'job_file_out': '/scratch/snx3000/akhosrav/submission_tests/_scheduler-stdout.txt', 
  'job_info_extra': 'Job info returned successfully', 
  'jobid': '54049703', 
  'name': 'aiida-45', 
  'nodelist': 'nid00083', 
  'nodes': '1', 
  'partition': 'normal', 
  'start_time': '0:01', 
  'state': 'CONFIGURING', 
  'time': '2024-06-21T10:44:44', 
  'time_left': '29:59', 
  'user': 'akhosrav'
}
```

**Comment by ekouts** [comment] 2024-06-24 12:57
Hi @khsrali, I think the issue is that you are re-using the same output and error files across jobs. Firecrest will try check the output and error file of the job, but in your case the file on the filesystem still has the content of another job. In your first job the state is still `PENDING` so nothing has been written yet by the job `54050460`.

Maybe something like this in your script would avoid these issues:
```
#SBATCH --error=job-%j.err
#SBATCH --output=job-%j.out
```

**Comment by khsrali** [comment] 2024-06-25 08:29
Hi @ekouts, thanks a lot for your answer, 
You are right, however, I think `Slurm` should overwrite those files on each new re-run. (maybe I'm wrong?)

In that case could it be that `FirecREST` is retrieving and parsing the existing out file, even before the new job being run or released from a queue ?

**Comment by ekouts** [comment] 2024-06-25 08:38
Yes, slurm will over-write the files as soon the job starts running (and while running). I am not sure what happens if two jobs are running simultaneously and they are pointing to the same file to be honest, I haven't tried 🤔 

> In that case could it be that FirecREST is retrieving and parsing the existing out file, even before the new job being run or released from a queue ?

Indeed, FirecREST will read the file (if available) every time you poll. And while pending it may show you results from an older run.

**Comment by khsrali** [comment] 2024-06-25 09:03
> I am not sure what happens if two jobs are running simultaneously and they are pointing to the same file to be honest, I haven't tried 🤔

Notice this scenario happens in a sequential manner:
Suppose first I submit a job with `SBATCH --output=job.out \n mpirun my_program` and it fails because there is a bug in `my_program`. Later I fix the bug, and submit it again without changing the submission script. Using the same submission script is a common practice among computational guys :))

In this scenario, when job is going for run, Slurm overwrites `job.out` by default (I just googled now :)). 

> Indeed, FirecREST will read the file (if available) every time you poll. And while pending it may show you results from an older run.

Would it be possible to add a condition to look for the file only if the states is not pending (or queuing)?
This would somehow reflect the behavior of `Slurm` that one would expect.

**Comment by khsrali** [comment] 2024-06-25 09:05
or maybe a condition that checks metadata of the file, if it was created before submission date.time, ignore.

**Comment by ekouts** [comment] 2024-06-25 09:23
Sure, sounds like a reasonable request. We will fix this in the next couple weeks and let you know :)

**Comment by ekouts** [comment] 2024-08-07 05:49
Hi @khsrali , this should be fixed in https://github.com/eth-cscs/firecrest/commit/844d60407798707ecb3294853ed473f9c15457b9 . Let us know if the behavior is not the expected.

**Closed by ekouts** 2024-08-07 05:49 UTC

**Comment by khsrali** [comment] 2024-08-07 06:08
Thanks @ekouts
Just had a quick look at https://github.com/eth-cscs/firecrest/commit/844d60407798707ecb3294853ed473f9c15457b9 looks good to me! (I haven't manually tested, though.)
